end2end_eval:
  metrics:
    text_block:
      metric:
        - Edit_dist
        # - BLEU
        # - METEOR
    display_formula:
      metric:
        - Edit_dist
        # - CDM_plain
    table:
      metric:
        - TEDS
        - Edit_dist
    reading_order:
      metric:
        - Edit_dist
  dataset:
    dataset_name: end2end_dataset
    ground_truth:
      data_path: ./doc_ocr_dataset/omnidocbench_1211_132_fixed.json
    prediction:
      data_path: ./doc_ocr_dataset/paddleocr-merged
    match_method: quick_match
